service: doc-app-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGODB_URL: ${env:MONGODB_URL}
    MONGODB_DBNAME: ${env:MONGODB_DBNAME}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
